MySQL:
  host: localhost
  user: root
  passwd: JONC
  db: fund
  port: 3306
  charset: utf8


Portfolio:
  risk_free: 0.035
  fit_frequency: BM
  portfolio_nbr: [3]


Filter:
  annual_return_score: 0.065
  cum_on_duty_term_pct: 0.60
  annual_return_fund: 0.06
  term: 1.5
  weighted_annual_return_score: 0.05
  mode: strict


NAVFile:
  nav_path: './data/1-fund_nav.csv'
  cur_path: './data/1-fund_nav_currency.csv'
  res_path: './data/processed_nav.dat'

ManagerFile:
  mana_his_path: './data/1-fund_managers_his.csv'
  mana_info_path: './data/1-fund_managers_info.csv'
  mana_chg_path: './data/1-fund_managers_chg.csv'
  res_mana_chg_path: './data/2-manger_chg.csv'
  res_mana_info_path: './data/2-mana_info.csv'

Backtest:
  pct: 0.6
  coe: 0.6